#!/usr/bin/env python3
"""
Ingest locally exported MinerU extraction results into MemU (RAG) only.

Flow:
1) Discover local extracted directories from export state file (preferred)
   or by scanning output root for *_extracted directories
2) Read and merge textual artifacts from extracted files
3) Chunk text and write chunks to MemU memory
4) Optionally ingest extracted images via MemU file endpoint
5) Persist progress state for resume/retry
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

try:
    import requests
except Exception:  # pragma: no cover - runtime guard
    requests = None  # type: ignore


DEFAULT_MEMU_BASE = "https://api.memu.so"
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".gif"}


@dataclass
class ExtractedImage:
    name: str
    data: bytes


@dataclass
class LocalExportJob:
    source_path: Path
    source_name: str
    data_id: str
    extract_dir: Path
    source_sha256: str
    fingerprint: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Ingest local MinerU extracted artifacts into MemU without re-uploading PDFs."
    )
    parser.add_argument(
        "--export-state-file",
        default=".cache/mineru_local_export_state.json",
        help="State file generated by mineru_pdf_export_local.py.",
    )
    parser.add_argument(
        "--extracted-root",
        default=".cache/mineru_exported",
        help="Fallback root directory to scan for *_extracted folders.",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Recursively scan --extracted-root for *_extracted directories.",
    )
    parser.add_argument("--max-files", type=int, default=0, help="Limit number of files, 0 means no limit.")
    parser.add_argument(
        "--state-file",
        default=".cache/mineru_local_to_memu_state.json",
        help="Progress state file path for local->MemU ingestion.",
    )
    parser.add_argument("--force", action="store_true", help="Re-ingest items even if already ingested.")
    parser.add_argument(
        "--fail-fast",
        action="store_true",
        help="Stop immediately on first MemU write failure (default is continue).",
    )
    parser.add_argument(
        "--ingest-images",
        action="store_true",
        help="Ingest extracted images into MemU using /memorize/file.",
    )
    parser.add_argument(
        "--max-images-per-file",
        type=int,
        default=0,
        help="Limit image ingestion per document, 0 means no limit.",
    )
    parser.add_argument(
        "--disable-image-anchor-text",
        action="store_true",
        help="Disable companion text memory per ingested image.",
    )
    parser.add_argument("--chunk-size", type=int, default=1600, help="Text chunk size in characters.")
    parser.add_argument("--chunk-overlap", type=int, default=200, help="Chunk overlap in characters.")
    parser.add_argument("--dry-run", action="store_true", help="Parse/chunk only, skip MemU writes.")

    parser.add_argument("--memu-base-url", default="", help="MemU base URL. Fallback config/env.")
    parser.add_argument("--memu-api-key", default="", help="MemU API key. Fallback config/env.")
    parser.add_argument(
        "--memu-api-style",
        default="",
        choices=["cloudV3", "localSimple", "sealosAssistant", "mem0V1"],
        help="MemU API style.",
    )
    parser.add_argument("--memu-endpoint-memorize", default="", help="Override memorize endpoint path.")
    parser.add_argument(
        "--memu-endpoint-memorize-file",
        default="",
        help="Override memorize file endpoint path (default localSimple: /memorize/file).",
    )
    parser.add_argument("--memu-user-id", default="", help="MemU user_id.")
    parser.add_argument("--memu-agent-id", default="", help="MemU agent_id.")
    parser.add_argument(
        "--memu-scope",
        default="papers",
        choices=["chat", "papers"],
        help="OpenIntern memory scope used to build default agent_id.",
    )
    parser.add_argument(
        "--memu-channel",
        default="cli",
        help="Default channel part for MemU user_id (<channel>:<chat_id>).",
    )
    parser.add_argument(
        "--memu-chat-id",
        default="pdf-import",
        help="Default chat_id part for MemU user_id (<channel>:<chat_id>).",
    )
    parser.add_argument(
        "--memu-timeout",
        type=int,
        default=0,
        help="MemU request timeout in seconds. 0 means config/env/default.",
    )
    parser.add_argument(
        "--memu-source-type",
        default="pdf",
        help="Source type tag for text memories (recommended: pdf/chat/image/file_text).",
    )
    parser.add_argument(
        "--memu-file-source-type",
        default="",
        help="Optional source_type for /memorize/file; defaults to --memu-source-type when empty.",
    )
    parser.add_argument(
        "--memu-local-include-agent-id",
        action="store_true",
        help="Include agent_id for localSimple/sealosAssistant payloads for legacy compatibility.",
    )
    parser.add_argument("--openintern-config", default="~/.openintern/config.json", help="OpenIntern config path for MemU defaults.")
    return parser.parse_args()


def require_requests() -> None:
    if requests is None:  # pragma: no cover - runtime guard
        raise SystemExit(
            "Missing dependency: requests. Install with: python3 -m pip install requests"
        )


def log(msg: str) -> None:
    print(msg, flush=True)


def normalize_path(value: str) -> Path:
    return Path(value).expanduser().resolve()


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def safe_data_id(path: Path, sha256_value: str) -> str:
    base = path.stem
    base = re.sub(r"[^A-Za-z0-9_.-]+", "_", base).strip("._-")
    if not base:
        base = "pdf"
    digest = sha256_value[:12]
    candidate = f"{base}_{digest}"
    return candidate[:120]


def parse_int(value: str, fallback: int) -> int:
    try:
        return int(str(value).strip())
    except Exception:
        return fallback


def load_openintern_memu_defaults(
    config_path: Path,
    scope: str,
    channel: str,
    chat_id: str,
) -> Dict[str, str]:
    config = read_json(config_path)
    memu = (((config.get("memory") or {}).get("memu") or {}) if isinstance(config, dict) else {})
    agent_id = str(memu.get("agentId") or "openintern").strip()
    scopes = memu.get("scopes") if isinstance(memu.get("scopes"), dict) else {}
    scope_suffix = str(scopes.get(scope) or scope).strip()
    scoped_agent = f"{agent_id}:{scope_suffix}" if scope_suffix else agent_id
    endpoints = memu.get("endpoints") if isinstance(memu.get("endpoints"), dict) else {}
    return {
        "base_url": str(memu.get("baseUrl") or "").strip(),
        "api_key": str(memu.get("apiKey") or "").strip(),
        "api_style": str(memu.get("apiStyle") or "").strip(),
        "scoped_agent_id": scoped_agent,
        "default_user_id": f"{channel}:{chat_id}",
        "endpoint_memorize": str(endpoints.get("memorize") or "").strip(),
        "endpoint_memorize_file": str(endpoints.get("memorizeFile") or "").strip(),
        "timeout_ms": str(memu.get("timeoutMs") or "").strip(),
    }


def resolve_memu_options(args: argparse.Namespace) -> Dict[str, Any]:
    scope = args.memu_scope.strip() or "papers"
    channel = args.memu_channel.strip() or "cli"
    chat_id = args.memu_chat_id.strip() or "pdf-import"
    config_defaults = load_openintern_memu_defaults(
        normalize_path(args.openintern_config),
        scope=scope,
        channel=channel,
        chat_id=chat_id,
    )

    memu_base = (
        args.memu_base_url.strip()
        or config_defaults.get("base_url", "")
        or str(os.getenv("MEMU_BASE_URL", "")).strip()
        or DEFAULT_MEMU_BASE
    )
    memu_key = (
        args.memu_api_key.strip()
        or config_defaults.get("api_key", "")
        or str(os.getenv("MEMU_API_KEY", "")).strip()
    )
    memu_style = (
        args.memu_api_style.strip()
        or config_defaults.get("api_style", "")
        or str(os.getenv("MEMU_API_STYLE", "")).strip()
        or "cloudV3"
    )
    memu_user = (
        args.memu_user_id.strip()
        or str(os.getenv("MEMU_USER_ID", "")).strip()
        or config_defaults.get("default_user_id", "")
    )
    memu_agent = (
        args.memu_agent_id.strip()
        or str(os.getenv("MEMU_AGENT_ID", "")).strip()
        or config_defaults.get("scoped_agent_id", "")
    )
    endpoint_memorize = (
        args.memu_endpoint_memorize.strip()
        or str(os.getenv("MEMU_ENDPOINT_MEMORIZE", "")).strip()
        or config_defaults.get("endpoint_memorize", "")
    )
    endpoint_memorize_file = (
        args.memu_endpoint_memorize_file.strip()
        or str(os.getenv("MEMU_ENDPOINT_MEMORIZE_FILE", "")).strip()
        or config_defaults.get("endpoint_memorize_file", "")
    )
    timeout_s = (
        args.memu_timeout
        if args.memu_timeout > 0
        else parse_int(str(os.getenv("MEMU_TIMEOUT_SECONDS", "")).strip(), 0)
    )
    if timeout_s <= 0:
        timeout_ms = parse_int(config_defaults.get("timeout_ms", ""), 0)
        timeout_s = max(1, int(timeout_ms / 1000)) if timeout_ms > 0 else 60
    timeout_s = max(timeout_s, 60)

    if not memu_user:
        raise ValueError("Missing memu user_id. Use --memu-user-id or set MEMU_USER_ID.")
    if memu_style in {"cloudV3", "mem0V1"} and not memu_agent:
        raise ValueError("Missing memu agent_id. Use --memu-agent-id or set MEMU_AGENT_ID.")
    if memu_style == "cloudV3" and not memu_key:
        raise ValueError("Missing memu api_key for cloudV3. Use --memu-api-key or set MEMU_API_KEY.")

    return {
        "base_url": memu_base,
        "api_key": memu_key,
        "api_style": memu_style,
        "user_id": memu_user,
        "agent_id": memu_agent,
        "endpoint_memorize": endpoint_memorize,
        "endpoint_memorize_file": endpoint_memorize_file,
        "timeout_s": timeout_s,
        "scope": scope,
        "source_type": args.memu_source_type.strip(),
        "file_source_type": args.memu_file_source_type.strip(),
        "local_include_agent_id": bool(args.memu_local_include_agent_id),
    }


class MemUIngestClient:
    def __init__(
        self,
        base_url: str,
        api_key: str,
        api_style: str,
        endpoint_memorize: str,
        endpoint_memorize_file: str,
        user_id: str,
        agent_id: str,
        default_source_type: str = "",
        default_file_source_type: str = "",
        local_include_agent_id: bool = False,
        timeout: int = 60,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key.strip()
        self.api_style = api_style
        self.user_id = user_id
        self.agent_id = agent_id
        self.default_source_type = default_source_type.strip()
        self.default_file_source_type = default_file_source_type.strip()
        self.local_include_agent_id = local_include_agent_id
        self.timeout = timeout
        local_styles = {"localSimple", "sealosAssistant"}

        if endpoint_memorize:
            self.endpoint_memorize = endpoint_memorize if endpoint_memorize.startswith("/") else f"/{endpoint_memorize}"
        else:
            if api_style in local_styles:
                self.endpoint_memorize = "/memorize"
            elif api_style == "mem0V1":
                self.endpoint_memorize = "/api/v1/memories"
            else:
                self.endpoint_memorize = "/api/v3/memory/memorize"

        if endpoint_memorize_file:
            self.endpoint_memorize_file = (
                endpoint_memorize_file
                if endpoint_memorize_file.startswith("/")
                else f"/{endpoint_memorize_file}"
            )
        else:
            self.endpoint_memorize_file = "/memorize/file" if api_style in local_styles else ""

        self.session = requests.Session()
        self.session.headers.update({"Accept": "application/json"})
        if self.api_key:
            self.session.headers["Authorization"] = f"Bearer {self.api_key}"

    def memorize(self, content: str, source_type: str = "") -> Dict[str, Any]:
        now_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        headers: Dict[str, str] = {"Content-Type": "application/json"}
        effective_source_type = source_type.strip() or self.default_source_type

        if self.api_style in {"localSimple", "sealosAssistant"}:
            payload: Dict[str, Any] = {
                "content": content,
                "user_id": self.user_id,
            }
            if effective_source_type:
                payload["source_type"] = effective_source_type
            if self.local_include_agent_id and self.agent_id:
                payload["agent_id"] = self.agent_id
        elif self.api_style == "mem0V1":
            payload = {
                "messages": [{"role": "user", "content": content}],
                "run_id": self.user_id,
                "metadata": {"agent_id": self.agent_id},
            }
            headers["X-User-Id"] = self.user_id
        else:
            payload = {
                "conversation": [{"role": "user", "content": content, "timestamp": now_iso}],
                "user_id": self.user_id,
                "agent_id": self.agent_id,
            }

        url = f"{self.base_url}{self.endpoint_memorize}"
        last_error: Optional[str] = None
        for attempt in range(1, 5):
            try:
                resp = self.session.post(url, json=payload, headers=headers, timeout=self.timeout)
                if resp.status_code >= 500:
                    raise RuntimeError(f"MemU HTTP {resp.status_code}: {resp.text[:400]}")
                if resp.status_code >= 400:
                    raise ValueError(f"MemU HTTP {resp.status_code}: {resp.text[:400]}")
                text = resp.text if resp.content else ""
                if not text.strip():
                    return {}
                try:
                    data = resp.json()
                except Exception:
                    return {"text": text[:1000]}
                return data if isinstance(data, dict) else {}
            except ValueError:
                raise
            except Exception as exc:
                last_error = f"{type(exc).__name__}: {exc}"
                if attempt >= 4:
                    suffix = f"; last_error={last_error}" if last_error else ""
                    raise RuntimeError(f"MemU memorize failed after retries: {url}{suffix}") from exc
                time.sleep(min(2 ** (attempt - 1), 8))
        raise RuntimeError("Unreachable")

    def memorize_file(self, file_name: str, file_bytes: bytes, source_type: str = "") -> Dict[str, Any]:
        if not self.endpoint_memorize_file:
            raise RuntimeError("MemU file memorize endpoint is not configured.")

        mime_type = mimetypes.guess_type(file_name)[0] or "application/octet-stream"
        effective_source_type = (
            source_type.strip()
            or self.default_file_source_type
            or self.default_source_type
        )
        files = {
            "file": (file_name, file_bytes, mime_type),
        }
        url = f"{self.base_url}{self.endpoint_memorize_file}"
        last_error: Optional[str] = None
        for attempt in range(1, 5):
            try:
                if self.api_style in {"localSimple", "sealosAssistant"}:
                    params: Dict[str, str] = {"user_id": self.user_id}
                    if effective_source_type:
                        params["source_type"] = effective_source_type
                    # Keep legacy compatibility for backends that read user_id/agent_id from form.
                    data: Dict[str, str] = {"user_id": self.user_id}
                    if self.local_include_agent_id and self.agent_id:
                        data["agent_id"] = self.agent_id
                    resp = self.session.post(
                        url,
                        params=params,
                        data=data,
                        files=files,
                        timeout=self.timeout,
                    )
                else:
                    data = {
                        "user_id": self.user_id,
                        "agent_id": self.agent_id,
                    }
                    resp = self.session.post(
                        url,
                        data=data,
                        files=files,
                        timeout=self.timeout,
                    )
                if resp.status_code >= 500:
                    raise RuntimeError(f"MemU HTTP {resp.status_code}: {resp.text[:400]}")
                if resp.status_code >= 400:
                    raise ValueError(f"MemU HTTP {resp.status_code}: {resp.text[:400]}")
                if not resp.content:
                    return {}
                try:
                    data_json = resp.json()
                except Exception:
                    return {"text": resp.text[:1000]}
                return data_json if isinstance(data_json, dict) else {}
            except ValueError:
                raise
            except Exception as exc:
                last_error = f"{type(exc).__name__}: {exc}"
                if attempt >= 4:
                    suffix = f"; last_error={last_error}" if last_error else ""
                    raise RuntimeError(f"MemU file memorize failed after retries: {url}{suffix}") from exc
                time.sleep(min(2 ** (attempt - 1), 8))
        raise RuntimeError("Unreachable")


def decode_bytes(data: bytes) -> str:
    for enc in ("utf-8", "utf-8-sig", "gb18030", "latin-1"):
        try:
            return data.decode(enc)
        except Exception:
            continue
    return data.decode("utf-8", errors="ignore")


def extract_json_strings(obj: Any, parent_key: str = "") -> List[str]:
    out: List[str] = []
    preferred_keys = (
        "text",
        "content",
        "markdown",
        "md",
        "html",
        "latex",
        "title",
        "abstract",
        "paragraph",
        "caption",
        "body",
    )

    if isinstance(obj, dict):
        for k, v in obj.items():
            out.extend(extract_json_strings(v, str(k).lower()))
    elif isinstance(obj, list):
        for item in obj:
            out.extend(extract_json_strings(item, parent_key))
    elif isinstance(obj, str):
        s = obj.strip()
        if len(s) < 12:
            return out
        if any(key in parent_key for key in preferred_keys) or len(s) >= 180:
            out.append(s)
    return out


def iter_files(root: Path) -> Iterable[Path]:
    for p in sorted(root.rglob("*")):
        if p.is_file():
            yield p


def folder_fingerprint(root: Path) -> str:
    hasher = hashlib.sha256()
    for p in iter_files(root):
        rel = str(p.relative_to(root)).replace("\\", "/")
        st = p.stat()
        hasher.update(rel.encode("utf-8", errors="ignore"))
        hasher.update(str(st.st_size).encode("ascii"))
        hasher.update(str(int(st.st_mtime)).encode("ascii"))
    return hasher.hexdigest()


def extract_dir_artifacts(extract_dir: Path) -> Tuple[str, List[ExtractedImage]]:
    files = [p for p in iter_files(extract_dir)]
    if not files:
        raise RuntimeError(f"No files found under extracted directory: {extract_dir}")

    def priority(path: Path) -> Tuple[int, str]:
        suffix = path.suffix.lower()
        order = {
            ".md": 0,
            ".markdown": 1,
            ".txt": 2,
            ".html": 3,
            ".json": 4,
            ".tex": 5,
            ".latex": 6,
        }
        return (order.get(suffix, 99), str(path))

    chunks: List[str] = []
    images: List[ExtractedImage] = []
    seen = set()
    for path in sorted(files, key=priority):
        rel = str(path.relative_to(extract_dir)).replace("\\", "/")
        suffix = path.suffix.lower()
        raw = path.read_bytes()
        if suffix in IMAGE_SUFFIXES:
            images.append(ExtractedImage(name=rel, data=raw))
            continue
        if suffix in {".md", ".markdown", ".txt", ".html", ".tex", ".latex"}:
            text = decode_bytes(raw).strip()
            if text:
                block = f"# File: {rel}\n\n{text}"
                if block not in seen:
                    chunks.append(block)
                    seen.add(block)
            continue

        if suffix == ".json":
            try:
                payload = json.loads(decode_bytes(raw))
            except Exception:
                continue
            strs = extract_json_strings(payload)
            if strs:
                text = "\n\n".join(strs)
                block = f"# File: {rel}\n\n{text}"
                if block not in seen:
                    chunks.append(block)
                    seen.add(block)

    if not chunks:
        raise RuntimeError(f"No textual content found in extracted directory: {extract_dir}")

    merged = "\n\n".join(chunks)
    merged = merged.replace("\r\n", "\n").replace("\r", "\n")
    merged = re.sub(r"\n{3,}", "\n\n", merged)
    return merged.strip(), images


def split_text_chunks(text: str, chunk_size: int, chunk_overlap: int) -> List[str]:
    if chunk_size <= 0:
        raise ValueError("chunk_size must be > 0")
    if chunk_overlap < 0:
        raise ValueError("chunk_overlap must be >= 0")
    if chunk_overlap >= chunk_size:
        raise ValueError("chunk_overlap must be smaller than chunk_size")

    src = text.strip()
    if not src:
        return []
    if len(src) <= chunk_size:
        return [src]

    chunks: List[str] = []
    start = 0
    min_cut = int(chunk_size * 0.6)
    while start < len(src):
        target = min(start + chunk_size, len(src))
        end = target
        if target < len(src):
            low = min(start + min_cut, len(src))
            segment = src[low:target]
            candidates = [
                segment.rfind("\n\n"),
                segment.rfind("\n"),
                segment.rfind("。"),
                segment.rfind(". "),
                segment.rfind(" "),
            ]
            best = max(candidates)
            if best > 0:
                end = low + best + 1
        if end <= start:
            end = min(start + chunk_size, len(src))
        part = src[start:end].strip()
        if part:
            chunks.append(part)
        if end >= len(src):
            break
        start = max(end - chunk_overlap, start + 1)
    return chunks


def build_memu_content(file_name: str, data_id: str, chunk_idx: int, chunk_total: int, chunk_text: str) -> str:
    return (
        f"[source_file={file_name}] [data_id={data_id}] [chunk={chunk_idx}/{chunk_total}]\n\n"
        f"{chunk_text}"
    )


def extract_image_anchor_snippet(merged_text: str, image_name: str, max_len: int = 320) -> str:
    idx = merged_text.find(image_name)
    if idx < 0:
        return ""
    start = max(0, idx - 260)
    end = min(len(merged_text), idx + 260)
    snippet = merged_text[start:end]
    snippet = re.sub(r"\s+", " ", snippet).strip()
    if len(snippet) > max_len:
        snippet = snippet[:max_len].rstrip() + "..."
    return snippet


def build_image_anchor_text(
    file_name: str,
    data_id: str,
    image_name: str,
    merged_text: str,
) -> str:
    snippet = extract_image_anchor_snippet(merged_text, image_name)
    base = (
        f"[source_file={file_name}] [data_id={data_id}] [image={image_name}] "
        "Image extracted from MinerU output and stored as multimodal memory."
    )
    if snippet:
        return f"{base}\n\nContext snippet: {snippet}"
    return base


def collect_jobs_from_export_state(state_file: Path) -> List[LocalExportJob]:
    state = read_json(state_file)
    files_obj = state.get("files", {}) if isinstance(state, dict) else {}
    if not isinstance(files_obj, dict):
        return []

    jobs: List[LocalExportJob] = []
    for key in sorted(files_obj.keys()):
        row = files_obj.get(key)
        if not isinstance(row, dict):
            continue
        if str(row.get("status") or "") != "exported":
            continue
        extract_dir_raw = str(row.get("extract_dir") or "").strip()
        if not extract_dir_raw:
            continue
        extract_dir = normalize_path(extract_dir_raw)
        if not extract_dir.exists() or not extract_dir.is_dir():
            continue

        source_path = normalize_path(key)
        source_name = str(row.get("file_name") or source_path.name).strip() or source_path.name
        source_sha = str(row.get("sha256") or "").strip()
        data_id = str(row.get("data_id") or "").strip()
        if not data_id:
            fallback_sha = source_sha or hashlib.sha256(str(source_path).encode("utf-8")).hexdigest()
            data_id = safe_data_id(Path(source_name), fallback_sha)
        fingerprint = folder_fingerprint(extract_dir)
        jobs.append(
            LocalExportJob(
                source_path=source_path,
                source_name=source_name,
                data_id=data_id,
                extract_dir=extract_dir,
                source_sha256=source_sha,
                fingerprint=fingerprint,
            )
        )
    return jobs


def collect_jobs_by_scan(extracted_root: Path, recursive: bool) -> List[LocalExportJob]:
    if not extracted_root.exists() or not extracted_root.is_dir():
        return []

    pattern = "**/*_extracted" if recursive else "*_extracted"
    dirs = sorted([p for p in extracted_root.glob(pattern) if p.is_dir()])
    jobs: List[LocalExportJob] = []
    for d in dirs:
        base_name = d.name[:-10] if d.name.endswith("_extracted") else d.name
        source_name = f"{base_name}.pdf"
        synthetic_source = d.with_name(source_name)
        source_sha = hashlib.sha256(str(synthetic_source).encode("utf-8")).hexdigest()
        data_id = safe_data_id(Path(source_name), source_sha)
        jobs.append(
            LocalExportJob(
                source_path=synthetic_source,
                source_name=source_name,
                data_id=data_id,
                extract_dir=d.resolve(),
                source_sha256="",
                fingerprint=folder_fingerprint(d),
            )
        )
    return jobs


def update_state_entry(state: Dict[str, Any], key: str, patch: Dict[str, Any]) -> None:
    files = state.setdefault("files", {})
    current = files.get(key) if isinstance(files, dict) else None
    if not isinstance(current, dict):
        current = {}
    current.update(patch)
    files[key] = current


def main() -> int:
    args = parse_args()
    require_requests()

    if args.chunk_size <= 0:
        raise SystemExit("--chunk-size must be > 0")
    if args.chunk_overlap < 0:
        raise SystemExit("--chunk-overlap must be >= 0")
    if args.chunk_overlap >= args.chunk_size:
        raise SystemExit("--chunk-overlap must be smaller than --chunk-size")

    export_state_file = normalize_path(args.export_state_file)
    extracted_root = normalize_path(args.extracted_root)
    ingest_state_file = normalize_path(args.state_file)
    ingest_state: Dict[str, Any] = read_json(ingest_state_file)
    if not ingest_state:
        ingest_state = {"version": 1, "files": {}}

    jobs = collect_jobs_from_export_state(export_state_file) if export_state_file.exists() else []
    discover_mode = "export-state"
    if not jobs:
        jobs = collect_jobs_by_scan(extracted_root, args.recursive)
        discover_mode = "scan"

    if args.max_files > 0:
        jobs = jobs[: args.max_files]

    if not jobs:
        log(
            "No extracted items found. "
            f"Checked export-state={export_state_file} and extracted-root={extracted_root}"
        )
        return 0

    memu_opts: Dict[str, Any] = {}
    memu_client: Optional[MemUIngestClient] = None
    if not args.dry_run:
        memu_opts = resolve_memu_options(args)
        memu_client = MemUIngestClient(
            base_url=memu_opts["base_url"],
            api_key=memu_opts["api_key"],
            api_style=memu_opts["api_style"],
            endpoint_memorize=str(memu_opts.get("endpoint_memorize") or "").strip(),
            endpoint_memorize_file=str(memu_opts.get("endpoint_memorize_file") or "").strip(),
            user_id=memu_opts["user_id"],
            agent_id=str(memu_opts.get("agent_id") or "").strip(),
            default_source_type=str(memu_opts.get("source_type") or "").strip(),
            default_file_source_type=str(memu_opts.get("file_source_type") or "").strip(),
            local_include_agent_id=bool(memu_opts.get("local_include_agent_id")),
            timeout=int(memu_opts.get("timeout_s", 60)),
        )
        if args.ingest_images and not memu_client.endpoint_memorize_file:
            raise SystemExit(
                "Image ingestion is enabled but MemU file endpoint is not configured. "
                "Use --memu-endpoint-memorize-file or configure localSimple/sealosAssistant /memorize/file."
            )

    ready_jobs: List[LocalExportJob] = []
    for job in jobs:
        state_key = str(job.extract_dir.resolve())
        previous = (ingest_state.get("files", {}) or {}).get(state_key, {})
        prev_fingerprint = str(previous.get("fingerprint") or "")
        prev_status = str(previous.get("status") or "")
        if not args.force and prev_status == "ingested" and prev_fingerprint == job.fingerprint:
            log(f"[SKIP] {job.source_name} already ingested from {job.extract_dir}")
            continue
        ready_jobs.append(job)

    if not ready_jobs:
        log("Nothing to ingest.")
        return 0

    log(
        f"Prepared {len(ready_jobs)} extracted items for MemU ingestion. "
        f"discovery={discover_mode}, chunk={args.chunk_size}/{args.chunk_overlap}"
    )
    if not args.dry_run:
        log(
            f"MemU target={memu_opts.get('base_url')} "
            f"user_id={memu_opts.get('user_id')} "
            f"agent_id={memu_opts.get('agent_id')} "
            f"scope={memu_opts.get('scope')} "
            f"source_type={memu_opts.get('source_type') or '(none)'} "
            f"file_source_type={memu_opts.get('file_source_type') or '(follow source_type)'} "
            f"endpoint_memorize={memu_opts.get('endpoint_memorize') or '/memorize'} "
            f"endpoint_memorize_file={memu_opts.get('endpoint_memorize_file') or '/memorize/file'}"
        )

    try:
        for job in ready_jobs:
            state_key = str(job.extract_dir.resolve())
            log("")
            log(f"[READ] {job.source_name} <- {job.extract_dir}")
            try:
                merged_text, extracted_images = extract_dir_artifacts(job.extract_dir)
            except Exception as exc:
                update_state_entry(
                    ingest_state,
                    state_key,
                    {
                        "status": "failed",
                        "error": f"parse failed: {exc}",
                        "source_path": str(job.source_path),
                        "source_name": job.source_name,
                        "data_id": job.data_id,
                        "extract_dir": str(job.extract_dir),
                        "fingerprint": job.fingerprint,
                        "updated_at": int(time.time()),
                    },
                )
                write_json(ingest_state_file, ingest_state)
                log(f"[FAILED] {job.source_name}: parse failed: {exc}")
                if args.fail_fast:
                    return 1
                continue

            chunks = split_text_chunks(merged_text, args.chunk_size, args.chunk_overlap)
            image_total = len(extracted_images)
            if args.max_images_per_file > 0:
                image_total = min(image_total, args.max_images_per_file)
            if not chunks:
                update_state_entry(
                    ingest_state,
                    state_key,
                    {
                        "status": "failed",
                        "error": "No text chunks generated from extracted directory.",
                        "source_path": str(job.source_path),
                        "source_name": job.source_name,
                        "data_id": job.data_id,
                        "extract_dir": str(job.extract_dir),
                        "fingerprint": job.fingerprint,
                        "images_total": image_total,
                        "updated_at": int(time.time()),
                    },
                )
                write_json(ingest_state_file, ingest_state)
                log(f"[FAILED] {job.source_name}: no chunks")
                if args.fail_fast:
                    return 1
                continue

            if args.dry_run:
                update_state_entry(
                    ingest_state,
                    state_key,
                    {
                        "status": "done",
                        "source_path": str(job.source_path),
                        "source_name": job.source_name,
                        "data_id": job.data_id,
                        "extract_dir": str(job.extract_dir),
                        "fingerprint": job.fingerprint,
                        "chunks_total": len(chunks),
                        "chunk_size": args.chunk_size,
                        "chunk_overlap": args.chunk_overlap,
                        "images_total": image_total,
                        "images_ingested": 0,
                        "updated_at": int(time.time()),
                    },
                )
                write_json(ingest_state_file, ingest_state)
                log(f"[DRY-RUN] {job.source_name}: chunks={len(chunks)} images={image_total}")
                continue

            if memu_client is None:
                raise RuntimeError("MemU client is not initialized.")

            previous_row = (ingest_state.get("files", {}) or {}).get(state_key, {})
            ingested = 0
            resume_ingested = 0
            if not args.force and isinstance(previous_row, dict):
                previous_status = str(previous_row.get("status") or "")
                previous_fingerprint = str(previous_row.get("fingerprint") or "")
                previous_total = int(previous_row.get("chunks_total") or 0)
                previous_ingested = int(previous_row.get("chunks_ingested") or 0)
                if (
                    previous_status == "failed"
                    and previous_fingerprint == job.fingerprint
                    and previous_total == len(chunks)
                    and previous_ingested > 0
                ):
                    resume_ingested = min(previous_ingested, len(chunks))
                    ingested = resume_ingested
                    if resume_ingested >= len(chunks):
                        log(f"[RESUME] {job.source_name}: text chunks already ingested, skip text writes")
                    else:
                        log(
                            f"[RESUME] {job.source_name}: continue from chunk {resume_ingested + 1}/{len(chunks)}"
                        )

            memu_error: Optional[str] = None
            for idx, chunk in enumerate(chunks, start=1):
                if idx <= resume_ingested:
                    continue
                payload = build_memu_content(
                    file_name=job.source_name,
                    data_id=job.data_id,
                    chunk_idx=idx,
                    chunk_total=len(chunks),
                    chunk_text=chunk,
                )
                try:
                    memu_client.memorize(
                        payload,
                        source_type=str(memu_opts.get("source_type") or "").strip(),
                    )
                except Exception as exc:
                    memu_error = f"chunk {idx}/{len(chunks)} failed: {exc}"
                    log(f"[MEMU-FAILED] {job.source_name}: {memu_error}")
                    if args.fail_fast:
                        raise
                    break
                ingested += 1
                if idx % 10 == 0 or idx == len(chunks):
                    log(f"[MEMU] {job.source_name}: {idx}/{len(chunks)}")

            if memu_error:
                update_state_entry(
                    ingest_state,
                    state_key,
                    {
                        "status": "failed",
                        "error": memu_error,
                        "source_path": str(job.source_path),
                        "source_name": job.source_name,
                        "data_id": job.data_id,
                        "extract_dir": str(job.extract_dir),
                        "fingerprint": job.fingerprint,
                        "chunks_total": len(chunks),
                        "chunks_ingested": ingested,
                        "chunk_size": args.chunk_size,
                        "chunk_overlap": args.chunk_overlap,
                        "images_total": image_total,
                        "images_ingested": 0,
                        "updated_at": int(time.time()),
                    },
                )
                write_json(ingest_state_file, ingest_state)
                continue

            images_ingested = 0
            image_error: Optional[str] = None
            if args.ingest_images and image_total > 0:
                previous_row = (ingest_state.get("files", {}) or {}).get(state_key, {})
                resume_images = 0
                if (
                    not args.force
                    and isinstance(previous_row, dict)
                    and str(previous_row.get("status") or "") == "failed"
                    and str(previous_row.get("fingerprint") or "") == job.fingerprint
                    and int(previous_row.get("chunks_ingested") or 0) >= len(chunks)
                    and int(previous_row.get("images_total") or 0) == image_total
                ):
                    prev_img_ingested = int(previous_row.get("images_ingested") or 0)
                    if prev_img_ingested > 0:
                        resume_images = min(prev_img_ingested, image_total)
                        images_ingested = resume_images
                        if resume_images >= image_total:
                            log(f"[RESUME] {job.source_name}: images already ingested, skip image writes")
                        else:
                            log(
                                f"[RESUME] {job.source_name}: continue from image {resume_images + 1}/{image_total}"
                            )

                for image_idx, image in enumerate(extracted_images[:image_total], start=1):
                    if image_idx <= resume_images:
                        continue
                    try:
                        memu_client.memorize_file(
                            file_name=Path(image.name).name,
                            file_bytes=image.data,
                            source_type=(
                                str(memu_opts.get("file_source_type") or "").strip()
                                or str(memu_opts.get("source_type") or "").strip()
                            ),
                        )
                        images_ingested += 1
                        if not args.disable_image_anchor_text:
                            anchor_text = build_image_anchor_text(
                                file_name=job.source_name,
                                data_id=job.data_id,
                                image_name=image.name,
                                merged_text=merged_text,
                            )
                            memu_client.memorize(
                                anchor_text,
                                source_type=str(memu_opts.get("source_type") or "").strip(),
                            )
                    except Exception as exc:
                        image_error = f"image {image_idx}/{image_total} ({image.name}) failed: {exc}"
                        log(f"[MEMU-IMAGE-FAILED] {job.source_name}: {image_error}")
                        if args.fail_fast:
                            raise
                        break

            if image_error:
                update_state_entry(
                    ingest_state,
                    state_key,
                    {
                        "status": "failed",
                        "error": image_error,
                        "source_path": str(job.source_path),
                        "source_name": job.source_name,
                        "data_id": job.data_id,
                        "extract_dir": str(job.extract_dir),
                        "fingerprint": job.fingerprint,
                        "chunks_total": len(chunks),
                        "chunks_ingested": ingested,
                        "chunk_size": args.chunk_size,
                        "chunk_overlap": args.chunk_overlap,
                        "images_total": image_total,
                        "images_ingested": images_ingested,
                        "updated_at": int(time.time()),
                    },
                )
                write_json(ingest_state_file, ingest_state)
                continue

            update_state_entry(
                ingest_state,
                state_key,
                {
                    "status": "ingested",
                    "source_path": str(job.source_path),
                    "source_name": job.source_name,
                    "data_id": job.data_id,
                    "extract_dir": str(job.extract_dir),
                    "fingerprint": job.fingerprint,
                    "chunks_total": len(chunks),
                    "chunks_ingested": ingested,
                    "chunk_size": args.chunk_size,
                    "chunk_overlap": args.chunk_overlap,
                    "images_total": image_total,
                    "images_ingested": images_ingested,
                    "updated_at": int(time.time()),
                },
            )
            write_json(ingest_state_file, ingest_state)
            log(f"[INGESTED] {job.source_name}: chunks={ingested} images={images_ingested}/{image_total}")

    except KeyboardInterrupt:
        write_json(ingest_state_file, ingest_state)
        log("\nInterrupted. State saved.")
        return 130
    except Exception as exc:
        write_json(ingest_state_file, ingest_state)
        log(f"\nERROR: {exc}")
        return 1

    write_json(ingest_state_file, ingest_state)
    total = len(ready_jobs)
    ingested = 0
    failed = 0
    for job in ready_jobs:
        row = (ingest_state.get("files", {}) or {}).get(str(job.extract_dir.resolve()), {})
        status = str((row or {}).get("status") or "")
        if status == "ingested":
            ingested += 1
        elif status == "failed":
            failed += 1

    log("")
    log(f"Finished. total={total}, ingested={ingested}, failed={failed}, state={ingest_state_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
